services:
  - type: web
    name: nestjs-app
    env: node
    plan: free
    buildCommand: yarn install && yarn run build
    startCommand: yarn run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: '3000'
      - key: DATABASE_URL

databases:
  - name: mongodb
    plan: free